name: base64_url_safe_uuid
description: A library for generating v4 UUIDs and encoding them into 22 character base64 URL-safe slug representation (based on RFC4648 sec5).
version: 1.0.1
repository: https://github.com/MominRaza/base64_url_safe_uuid
issue_tracker: https://github.com/MominRaza/base64_url_safe_uuid/issues
topics:
  - uuid
  - base64
  - urls
  - links

environment:
  sdk: ^3.4.3

dependencies:
  uuid: ^4.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
