name: base64_url_safe_uuid
description: A library to generate base64 url safe UUIDs.
version: 1.0.0
repository: https://github.com/MominRaza/base64_url_safe_uuid

environment:
  sdk: ^3.4.3

dependencies:
  uuid: ^4.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
